[window]
padding = { x = 23, y = 23 }

[font]
normal = { family = "CozetteVector", style = "Regular" }
bold = { family = "CozetteVector", style = "Regular" }
size = 10


[colors.primary]
background            = "#282828"
foreground            = "#ffffff"
dim_foreground        = "#282828"
bright_foreground     = "#ffffff"

[colors.cursor]
text                  = "#ffffff"
cursor                = "#ffffff"

[colors.vi_mode_cursor]
text                  = "#ffffff"
cursor                = "#ffffff"

[colors.search.matches]
foreground            = "#ffffff"
background            = "#111111"

[colors.search.focused_match]
foreground            = "#ffffff"
background            = "#111111"

[colors.hints.start]
foreground            = "#ffffff"
background            = "#111111"

[colors.hints.end]
foreground            = "#ffffff"
background            = "#111111"

[colors.line_indicator]
#foreground            = "None"
#background            = "None"

[colors.footer_bar]
foreground            = "#ffffff"
background            = "#111111"

[colors.selection]
text                  = "#ffffff"
background            = "#111111"

[colors.normal]
black                 = "#ffffff"
red                   = "#ffffff"
green                 = "#ffffff"
yellow                = "#ffffff"
blue                  = "#ffffff"
magenta               = "#ffffff"
cyan                  = "#ffffff"
white                 = "#ffffff"

[colors.bright]
black                 = "#ffffff"
red                   = "#ffffff"
green                 = "#ffffff"
yellow                = "#ffffff"
blue                  = "#ffffff"
magenta               = "#ffffff"
cyan                  = "#ffffff"
white                 = "#ffffff"

[colors.dim]
black                 = "#ffffff"
red                   = "#ffffff"
green                 = "#ffffff"
yellow                = "#ffffff"
blue                  = "#ffffff"
magenta               = "#ffffff"
cyan                  = "#ffffff"
white                 = "#ffffff"

[cursor.style]
shape = "Beam"
